# Generated by Django 2.2.3 on 2019-07-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_articlepost_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
    ]
